
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 7;
  public static final int MENQUE = 21;
  public static final int INTERROGACION = 14;
  public static final int POR = 17;
  public static final int IMPRIMIR = 44;
  public static final int ENTERO = 48;
  public static final int PRSINO = 33;
  public static final int LLAVIZQ = 12;
  public static final int PRCORTAR = 37;
  public static final int NOIGUAL = 26;
  public static final int IDENTIFICADOR = 51;
  public static final int NOT = 29;
  public static final int AND = 28;
  public static final int IGUAL = 25;
  public static final int CARACTER = 47;
  public static final int CORDER = 11;
  public static final int DIVIDIDO = 18;
  public static final int PRCONTINUAR = 41;
  public static final int OR = 27;
  public static final int PRHACER = 40;
  public static final int INCREMENTO = 30;
  public static final int MAYIGUAL = 23;
  public static final int UMENOS = 52;
  public static final int PRVOID = 43;
  public static final int DECIMAL = 49;
  public static final int PRSI = 32;
  public static final int EOF = 0;
  public static final int PARIZQ = 8;
  public static final int PREJECUTAR = 45;
  public static final int PRPORDEFECTO = 36;
  public static final int DECREMENTO = 31;
  public static final int error = 1;
  public static final int COMA = 5;
  public static final int CADENA = 46;
  public static final int MODULO = 20;
  public static final int MENOS = 16;
  public static final int TPDATO = 2;
  public static final int MAYQUE = 22;
  public static final int ASIGNACION = 3;
  public static final int POTENCIA = 19;
  public static final int LLAVDER = 13;
  public static final int PRSELECTOR = 34;
  public static final int PRPARA = 38;
  public static final int PUNTO = 6;
  public static final int MENIGUAL = 24;
  public static final int BOOLEANO = 50;
  public static final int PTCOMA = 4;
  public static final int PRCASO = 35;
  public static final int PARDER = 9;
  public static final int PRMIENTRAS = 39;
  public static final int CORIZQ = 10;
  public static final int PRRETORNO = 42;
  public static final int MAS = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TPDATO",
  "ASIGNACION",
  "PTCOMA",
  "COMA",
  "PUNTO",
  "DOSPUNTOS",
  "PARIZQ",
  "PARDER",
  "CORIZQ",
  "CORDER",
  "LLAVIZQ",
  "LLAVDER",
  "INTERROGACION",
  "MAS",
  "MENOS",
  "POR",
  "DIVIDIDO",
  "POTENCIA",
  "MODULO",
  "MENQUE",
  "MAYQUE",
  "MAYIGUAL",
  "MENIGUAL",
  "IGUAL",
  "NOIGUAL",
  "OR",
  "AND",
  "NOT",
  "INCREMENTO",
  "DECREMENTO",
  "PRSI",
  "PRSINO",
  "PRSELECTOR",
  "PRCASO",
  "PRPORDEFECTO",
  "PRCORTAR",
  "PRPARA",
  "PRMIENTRAS",
  "PRHACER",
  "PRCONTINUAR",
  "PRRETORNO",
  "PRVOID",
  "IMPRIMIR",
  "PREJECUTAR",
  "CADENA",
  "CARACTER",
  "ENTERO",
  "DECIMAL",
  "BOOLEANO",
  "IDENTIFICADOR",
  "UMENOS"
  };
}

